### ISSUE TITLE
Right to left scrollView 

### ISSUE THREAD

**Issue by almatri** [hyperoslo/Lightbox#101]
I have an app that is localized to Arabic which make the layouts from the right to the left
And I have a collection view with images (from right to left) as in this image 
https://i.suar.me/8qoM/m

The problem is when I view the last image (the image on the most left with index = 3) with light box
it is shown as the most right image in Lightbox scroll view 

Another ex:
in collection view
3 2 1 0
in Lightbox scroll view 
0 1 2 3

how can I change this behavior?

**Comment by zenangst** [comment]
@almatri hey man, could you just start the light box at the last index of the collection using the `goTo` method?
