### ISSUE TITLE
Screen is half-black after dismissal

### ISSUE THREAD

**Issue by rmnblm** [hyperoslo/Lightbox#102]
Hi there,

I'm facing a weird issue after you do the following steps:

1. Tap on an image while your phone is in **portrait mode**
2. Turn your phone to **landscape**
3. Zoom into the picture
4. Zoom out
5. Close the image by swiping or pressing the close button

My code looks like this:

``` swift
let lightboxController = LightboxController(images: [LightboxImage(image: image)])
LightboxConfig.PageIndicator.enabled = false
LightboxConfig.hideStatusBar = true
present(lightboxController, animated: true, completion: nil)
```

What happens is this:

![unadjustednonraw_thumb_2f6d](https://cloud.githubusercontent.com/assets/5942764/23498338/a18f5a74-ff27-11e6-857b-b288b379e30a.jpg)

To resolve the issue on the iPhone, you have to close the app in the Task Manager and open the app again.

**Comment by onmyway133** [comment]
@rmnblm can confirm this is the problem
