### ISSUE TITLE
LightboxConfig initializer is inaccesible due to 'internal' protection level

### ISSUE THREAD

**Issue by JesusAdolfo** [hyperoslo/Lightbox#105]
I had this issue using the hyperoslo/imagePicker as well. However, updating to the latest release solved the issue. On the other hand, trying the same with hyperoslo/Lightbox didn't do it.

Trying to to initialize LightboxConfig:

`var lightboxConfig = LightboxConfig()
`
⚠️ Causes the following error:
LightboxConfig initializer is inaccesible due to 'internal' protection level

I need access to the LightboxConfig to change the texts for the buttons

**Comment by heisen273** [comment]
try this:
LightboxConfig.CloseButton.text = "ButtonName"

**Comment by JesusAdolfo** [comment]
@heisen273 how could I do that if I can not instantiate lightboxConfig on the first place? 
It is not a warning but an error

**Comment by vadymmarkov** [comment]
@JesusAdolfo You don't need to instantiate `LightboxConfig`, everything is static there.
