### ISSUE TITLE
VERY BAD BUG: Crippled parent view after device rotation

### ISSUE THREAD

**Issue by mjneusta** [hyperoslo/Lightbox#106]
This bug is even present in the online demo:
1. Click on "Show me the lightbox"
2. Double-Click or zoom in image
3. Rotate Device 90 degrees (first anomaly: image is much too small now)
4. Press close button

Now the parent view has wrong dimensions. I guess the width equals height.

**Comment by zenangst** [comment]
Hey @mjneusta, so just to clarify a bit. This bug appears in the demo when you go into lightbox, rotate and then close lightbox. This leads me to believe that it's not really a light box bug per say but a flaw in the demo? 😎

**Comment by onmyway133** [comment]
@mjneusta Hi, do you have the latest Lightbox? Since Lightbox is not officially released yet, can you checkout master? This https://github.com/hyperoslo/Lightbox/pull/103 may fix your problem

**Comment by mjneusta** [comment]
@onmyway133 The problem exists in pod 1.0.0 and it seems to be fixed with the #103 related commit.
Using this entry in my Podfile temporary helps:
`        pod 'Lightbox', :git => 'https://github.com/hyperoslo/Lightbox.git', :commit => 'eb44c67f69968f979fd1d141c7f52697904c3858'
`
Thank you!

**Comment by onmyway133** [comment]
@mjneusta Glad that it works for you. I will close this issue for now 🙂
