### ISSUE TITLE
imageView frames (and therefore activityIndicator frames) improperly placed while waiting for images to download.

### ISSUE THREAD

**Issue by andrewbellay** [hyperoslo/Lightbox#108]
First off, thanks for the nice repo guys :)

So I have uncovered an issue when viewing an imageView while waiting for an image to download.

I'm presenting the lightboxController and then immediately going to the image that the user selected from my previous UI:

```
lightboxVC.goTo(index, animated: false)
present(lightboxVC, animated: true)
```

If the index is 0 (the first image) then, the activityIndicator shows up and behaves as expected, and disappears as the downloaded image is displayed. However, if I either 1) swipe to the next photo which is still being downloaded or 2) my index (above) is greater than 0, then the activity indicator doesn't appear.

It took me a while just to figure out the problem but I think I have a clear description of it and a potential solution. _In short the problem is that the frames of the imageView aren't being set properly when there's not yet an image._

All of the attached screenshots are supposed to have 9 images total and I'm focused on the 5th image in each case. I used images with numbers to help us out here...

**Improperly placed imageViews (before images download):**
![screenshot 2017-04-25 00 44 48](https://cloud.githubusercontent.com/assets/694295/25376218/40ceadba-2958-11e7-89c6-8b7fd65be7fd.png) Note that the imageViews skip every other slot while their images are downloading. Again, the focus is on the 5th slot (with the black background). The activityIndicators are the gray dots.

**Properly placed imageViews (after images download):**
![screenshot 2017-04-25 00 45 17](https://cloud.githubusercontent.com/assets/694295/25376059/bcca337c-2957-11e7-9d45-a8664f1b00e0.png) Note that the imageViews become properly placed once there's an image.

I believe the fix is to add:
`centerImageView()`

to the guard-else statement (near ln 134 of PageView.swift):
`guard let image = imageView.image else { return }`

in:
`func configureImageView()`

yielding:
```
guard let image = imageView.image else {
	centerImageView()
	return
}
```

This seems to properly place the imageViews, even when they don't have images yet.

**Properly placed imageViews (during image download):**
![screenshot 2017-04-25 01 32 24](https://cloud.githubusercontent.com/assets/694295/25376070/ca06f3ae-2957-11e7-8824-33f6f37cfd8d.png)

Hope this helps to quickly test this bug and fix and then get this code pushed live!

Maybe this activityIndicator code can get some attention too??
https://github.com/hyperoslo/Lightbox/tree/fix/loading_view

**Comment by andrewbellay** [comment]
hello?

**Comment by zenangst** [comment]
Hey @andrewbellay, sorry for not responding earlier. Wow kudos on the super descriptive issue. It looks like you are on to something there. We will do some investigate on the matter but one thing that I would prefer is for you to make a PR to include a fix. The love to review code and want everyone to be a part of making Lightbox super great!

With that said, we are a bit busy with new projects and deadlines at the moment, so if we were to look at it, it might take more time than if you submit a PR that we can just review while we pour black gold aka coffee down our troughs in the morning 😎

**Comment by onmyway133** [comment]
@andrewbellay Hi, it seems https://github.com/hyperoslo/Lightbox/pull/120 fixed the issue. We will release new version after the Swift 4 transition 🥂
