### ISSUE TITLE
Crash while cutting an info label, which has emojies

### ISSUE THREAD

**Issue by vitalii-tym** [hyperoslo/Lightbox#114]
Looks like it can't make a new range. See screenshot.
![screenshot 2017-06-19 14 26 20](https://user-images.githubusercontent.com/5410835/27283265-21cb5dbc-54fc-11e7-8849-62a672a0651b.png)

**Comment by onmyway133** [comment]
@vitalii-tym Hi, thanks for your issue and catching with this. Mind making a PR 😉 ?
