### ISSUE TITLE
Progress indicator appears too late for images loaded from URL if the very first image in a row was inited as UIImage

### ISSUE THREAD

**Issue by vitalii-tym** [hyperoslo/Lightbox#116]
STR:
1. Make sure there are no images cached (f.e. do Reset Content and Settings for simulator)
2. In the demo project put photo1 at the first place, so that the array of lighboxImages will be "photo1", URL, "photo3", "photo4"
3. Imitate a bad network quality with settings similar to DSL network for example
4. Open the demo project, tap "Show me the lighbox" and quickly slide to the next image (which is supposed to be loaded from URL)

Result: There are no progress indication while image is being loaded. If you wait for some time, the progress indication will blink right before the image appears.

P.S. I'll try to do a PR later if I have time.

**Comment by vitalii-tym** [comment]
This issue seems very similar to what happens in https://github.com/hyperoslo/Lightbox/issues/108
Probably even a duplicate.

**Comment by onmyway133** [comment]
@vitalii-tym Hi, yeah, it is duplication. We will fix this in the swift 4 migration
