### ISSUE TITLE
How to remove grey circle background behind ActivityIndicatorView

### ISSUE THREAD

**Issue by chanonly123** [hyperoslo/Lightbox#124]
How to remove grey circle background behind ActivityIndicatorView?

**Comment by onmyway133** [comment]
@chanonly123 Hi, sorry for late response. During the swift 4 migration, we've decided that to allow more flexibility, the loading indicator can be configurable. You can take a look here https://github.com/hyperoslo/Lightbox/pull/136. Also, the status of swift 4 migration can be viewed here https://github.com/hyperoslo/Lightbox/tree/swift4, feel free to comment or review 😉
