### ISSUE TITLE
When multitasking on iPad, layout is incorrect

### ISSUE THREAD

**Issue by SkylerSeamans** [hyperoslo/Lightbox#130]
When using Slide Over multitasking on iPad, the frames are sized for the iPad screen size instead of the actual size of the view. This results in photos being out of bounds and paging is broken.

**Comment by onmyway133** [comment]
@SkylerSeamans Hi, can you show us the screenshot?

**Comment by SkylerSeamans** [comment]
Hi,

I added a screen recording showing what I'm seeing. If Lightbox is presented _after_ the app starts multitasking, the images are sized incorrectly and paging doesn't work. If the Lightbox view is presented _before_ multitasking, the images are correct. I've included both cases in the screen recording. The 1st case occurs 1st in the video. Hope that helps! I've also attached two screenshots. In the 1st screenshot, you can see how the image should look (it's a neon sign). In the 2nd screen shot, you can see how it appears in multitasking.

![screen shot 2017-10-05 at 5 03 22 pm](https://user-images.githubusercontent.com/3864580/31254942-3f2d23ec-a9f0-11e7-8253-348f81654a13.png)
![screen shot 2017-10-05 at 5 03 28 pm](https://user-images.githubusercontent.com/3864580/31254941-3f1923a6-a9f0-11e7-8e18-516988660bc8.png)

[LightboxScreenRecording.zip](https://github.com/hyperoslo/Lightbox/files/1361004/LightboxScreenRecording.zip)
