### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by jlaws** [hyperoslo/Lightbox#133]
Any plans to update to Swift 4?

**Comment by onmyway133** [comment]
@jlaws Hi, thanks for asking. We're migrating dependencies https://github.com/hyperoslo/Imaginary and https://github.com/hyperoslo/Hue, then we will migrate `Lightbox` to Swift 4. Will keep you posted

**Comment by onmyway133** [comment]
@jlaws Hi, we're currently migrating things to swift 4, you can check the branch here https://github.com/hyperoslo/Lightbox/tree/swift4 🥂  feed free to review
