### ISSUE TITLE
Hue dependency - Xcode 9 / Swift 3

### ISSUE THREAD

**Issue by TParizek** [hyperoslo/Lightbox#137]
Hi,
thanks for awesome library. I have project written in Swift 3.2, deployment target iOS 9.0 and Xcode 9 and I've run into problem with Hue dependency. When I try to build project, I get error at import Hue - Module file's minimum deployment target is ios9.0 v9.0. I looked at Hue github and it is already updated to Swift 4 on master, could it be the problem?

Thanks,
Tomas

**Comment by onmyway133** [comment]
@TParizek Hi, that's maybe because the podspec hasn't locked version of Hue https://github.com/hyperoslo/Lightbox/blob/master/Lightbox.podspec. We will fix this

**Comment by xploit42** [comment]
Hello, I've the same issue, when do you think will it be solved?

Thanks,

Cédric

**Comment by xploit42** [comment]
@TParizek: As a workaround you can change the version of HUE in you podfile.lock from 3.0.0 to 2.0.1 and then run pod install.

Cédric

**Comment by TParizek** [comment]
@xploit42 Thanks!

I made a [pull request](https://github.com/hyperoslo/Lightbox/pull/138) with this fix.

**Comment by onmyway133** [comment]
@TParizek thanks for the PR
@TParizek @xploit42 sorry for the confusion. We've published 1.1.0 https://github.com/hyperoslo/Lightbox/releases/tag/1.1.0 which locks dependencies version. You can check that
