### ISSUE TITLE
Build with compile issues.

### ISSUE THREAD

**Issue by kevinlee85** [hyperoslo/Lightbox#140]
I am just update Lightbox to 2.0.0, but build with below compile error:
`Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'`

**Comment by zenangst** [comment]
Where do you get this error? Could you share some code snippets so that we have a bit more to work with? At first glance it just looks like you are giving it the wrong types :)

**Comment by dcortright** [comment]
`open fileprivate(set) lazy var closeButton: UIButton = { [unowned self] in
    let title = NSAttributedString(
      string: LightboxConfig.CloseButton.text,
      attributes: LightboxConfig.CloseButton.textAttributes)`

I am getting the same error. The code above is one of the places that I see it. The attributes just need to be cast as `[String: Any]` but I do not wish to override the pod. Below is the suggested fix from Xcode: 

`open fileprivate(set) lazy var closeButton: UIButton = { [unowned self] in
    let title = NSAttributedString(
      string: LightboxConfig.CloseButton.text,
      attributes: LightboxConfig.CloseButton.textAttributes as [String : Any])`

**Comment by onmyway133** [comment]
@kevinlee85 maybe you can check @dcortright 's suggestion ?
