### ISSUE TITLE
Open ImagePicker or Gallery from Lightbox example

### ISSUE THREAD

**Issue by sverin** [hyperoslo/Lightbox#141]
Is there a way from Lightbox to open ImagePicker or Gallery? Examples in the other projects shows how to open Lightbox from them, but I want to do the other way around.

The users in my app should be able to add one or more images, view them and possibly add more in another session. So I wanted to use Lightbox as a image gallery to view images, and then ImagePicker or Gallery to add more images. But I want be able to add more images from Lightbox and I can't figure it out.

**Comment by onmyway133** [comment]
@sverin Hi, your use case is a bit special. Maybe you can just add some buttons inside `headerView` of `Lightbox`, and trigger the action to open `ImagePicker` or `Gallery`?

**Comment by sverin** [comment]
Okay, figured it out. I'll try both ways and see what works best. Thanks for a set of awesome libraries. Keep up the great work.
