### ISSUE TITLE
pod update

### ISSUE THREAD

**Issue by Stefanhym** [hyperoslo/Lightbox#142]
hi, plz update pod, since it's still the old one

**Comment by onmyway133** [comment]
@Stefanhym Hi, Lightbox points to 2.0.0 on Cocoapods https://cocoapods.org/?q=lightbox, maybe you need to reset your Cocoapods cache, or check the version in Podfile.lock?

**Comment by Stefanhym** [comment]
thx, problem solved. 
Clear the cache.
