### ISSUE TITLE
Feature request: Possibility to add a UIView to a page

### ISSUE THREAD

**Issue by sverin** [hyperoslo/Lightbox#145]
Would it not be great if the library also could display a UIView as a page?
Maybe extend the LightboxImage class with the possibility to add a UIView?

**Comment by zenangst** [comment]
Hey @sverin, could you explain a bit more in-depth what that kind of feature would give you? I mean, what are you trying to achieve?

**Comment by sverin** [comment]
Hi @zenangst , I've implemented the Lightbox in the following way.

1. The Lightbox gallery initialize with a couple of images.
2. The last image is at the moment a generated image and adds the possibility to add more images through Gallery. 

This image is generated from a programmatically UIView and then converted with UIGraphicsImageRenderer. This works great for my purpose. However, I feel that I would be great to add UIView's as well as UIImage's. But maybe it's out of scope of the project, since it's an image gallery?

See attached video.
[lightbox_example.zip](https://github.com/hyperoslo/Lightbox/files/1385512/lightbox_example.zip)
