### ISSUE TITLE
SwiftHash is missing in Carthage-Build

### ISSUE THREAD

**Issue by papierschiff** [hyperoslo/Lightbox#146]
When i try to build the latest version with carthage i get the error:

> Failed to read file or folder at /.../Carthage/Checkouts/Lightbox/Carthage/Build/iOS/SwiftHash.framework

I think it is because the dependency Imaginary uses Cache (https://github.com/hyperoslo/Cache) this is not pinned to a specific version. Since some days the Cache-project includes swiftHash in an other way since before.

I created a fork https://github.com/papierschiff/Lightbox which uses a pinned version to a forked Imaginary repo which ha a pinned Cache-dependency.

Stats: Xcode 9.1, Carthage 0.26.2, latest Lightbox build

**Comment by onmyway133** [comment]
@papierschiff Hi, I've fixed `Cartfile` in `Imaginary`, and update `Lightbox`. Can you try https://github.com/hyperoslo/Lightbox/releases/tag/2.0.1? Can you also try

```
rm -rf Carthage
Cartfile.resolved
carthage update

```

**Comment by papierschiff** [comment]
Looks good from my side, thank you very much!
