### ISSUE TITLE
README outdated?

### ISSUE THREAD

**Issue by daviskoh** [hyperoslo/Lightbox#148]
Version: 2.0.1
Swift 4

The README says that you can do custom image loading which is what I need given that my assets are private in S3 and not exposed to world via HTTP.

```
LightboxConfig.loadImage = {
  imageView, URL, completion in
  // Custom image loading
}
```

However, I am getting a compiler error saying `Type 'LightboxConfig' has no member 'loadImage'` and rightfully so as I am not seeing any mention of `loadImage` in the source code. 

Is this still a supported feature or are the docs outdated?

**Comment by MMOmaster35** [comment]
I need to know this to. I use this feature and it would be a problem if it was no longer available.

**Comment by dimidrollko** [comment]
Same.

**Comment by onmyway133** [comment]
@MMOmaster35 @dimidrollko @daviskoh Hi, you can check https://github.com/hyperoslo/Lightbox/releases/tag/2.1.0
