### ISSUE TITLE
Value of type 'Image' has no member 'uimage'

### ISSUE THREAD

**Issue by cwestMobile** [hyperoslo/Lightbox#149]
let lightboxImages = images.flatMap { $0.uimage(ofSize: UIScreen.main.bounds.size)}.map({ LightboxImage(image: $0 )})

This line has the following error in your demo project: Value of type 'Image' has no member 'uimage'

Please post a fix/idea for fix. Thanks.

**Comment by onmyway133** [comment]
You have filed the issue on Gallery https://github.com/hyperoslo/Gallery/issues/63. I will close this for now

**Comment by Vashishth2003** [comment]
value of type '[IMGGallery]' has no member 'galleryimg' solve this error
