### ISSUE TITLE
Using UIWindow for layout size

### ISSUE THREAD

**Issue by andreyrd** [hyperoslo/Lightbox#150]
[LightboxController:261](https://github.com/hyperoslo/Lightbox/blob/master/Source/LightboxController.swift#L261) attempts to get the size for the scroll view from `UIApplication.shared.delegate?.window??.bounds.size`, which assumes that you have that implemented.

Maybe something like `UIApplication.shared.keyWindow` could be used instead? I'm not sure if implementing `UIApplicationDelegate.window` is a common enough convention that this issue doesn't matter, but it's definitely something I ran into! :)

Edit:
I can open a PR that uses `UIApplication.shared.keyWindow` if I get the go ahead. Perhaps I can even have it use `keyWindow` just as a `??` fallback.

**Comment by onmyway133** [comment]
@andreyrd Hi, we have decided to not use UIWindow to frame, but instead using view of presented ViewController, which is `LightBoxController`. You can check https://github.com/hyperoslo/Lightbox/releases/tag/2.1.0

**Comment by andreyrd** [comment]
Hey, thanks! But it looks like it's still being used as a default value for `size` in the `configureLayout` method signature, now at this line [LightboxController:274](https://github.com/hyperoslo/Lightbox/blob/master/Source/LightboxController.swift#L274).

It looks like this `size` defines the frame of the scroll view, and if I don't implement `UIApplicationDelegate.window`, my scroll view stays at size zero.

**Comment by onmyway133** [comment]
@andreyrd It shouldn't depend on the size of the `UIWindow`, since it's presented view controller. I can fix that, or do you want to submit a PR 😉 ?
