### ISSUE TITLE
FooterView doesn't show up at start

### ISSUE THREAD

**Issue by jsntfv** [hyperoslo/Lightbox#159]
Great library!  This is my first time posting in GitHub.  
The latest updates take care of the safe area issues for the iPhone X, but I noticed that the footer view doesn't show up when the Lightbox view appears for the first time.  I used this in the viewDidAppear method to display the footer at start:
```         
if #available(iOS 11.0, *) {
       configureLayout(view.safeAreaLayoutGuide.layoutFrame.size)
} else {
      configureLayout(view.bounds.size)
}
```

**Comment by onmyway133** [comment]
@jsntfv Hi, does it happen for you in the demo app? I don't see the problem

![simulator screen shot - iphone x - 2017-11-22 at 09 38 23](https://user-images.githubusercontent.com/2284279/33117481-ea12ef06-cf68-11e7-8a97-5888641e74bf.png)

**Comment by jsntfv** [comment]
Hi @onmyway133, 
I am using Xcode 9.2 beta.  I tried the demo app and got the same result in the iPhone X simulator.  Then I tried Xcode 9.1 and that is when I found out the difference between iOS11.1 and iOS11.2. I  consistently have the footer view missing with devices on iOS11.2 but not on iOS11.1
But if I rotate the device, the footer view appears when using iOS11.2.  I hope this helps.

**Comment by onmyway133** [comment]
@jsntfv I'm not using beta so I don't know, but I will wait for the final version of 9.2, then I will check

**Comment by jsntfv** [comment]
Thank you

**Comment by annjawn** [comment]
I am facing the same issue. Infact in my case the footer view briefly shows up when the Close button is tapped.

**Comment by annjawn** [comment]
I think this issue needs to be re-opened @onmyway133 ... I had to finally do this `y: view.bounds.height - footerView.frame.height - 100` in `LightBoxController.swift` for the footer view to show up. Otherwise, the footerview is showing up but it's too low in the scrollview that it's not even visible. I might change the `100` to a slightly smaller number for now.

```
open override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()

    scrollView.frame = view.bounds
    footerView.frame = CGRect(
      x: 0,
      y: view.bounds.height - footerView.frame.height - 100,
      width: view.bounds.width,
      height: 100
    )

    headerView.frame = CGRect(
      x: 0,
      y: 16,
      width: view.bounds.width,
      height: 100
    )
  }
```

**Comment by annjawn** [comment]
You know what...nevermind. I think it's a simulator bug. 😊 It works fine on the devices.
