### ISSUE TITLE
Crash on IOS 11.1.1 (15B150)

### ISSUE THREAD

**Issue by talk2cerlin** [hyperoslo/Lightbox#162]
We have got a crash on IOS 11.1.1 (15B150) iPhone SE

 i have attached the logs below

	Crashed: com.apple.main-thread
	0  Lightbox                       0x1051ddecc _TFC8Lightbox9InfoLabelgP33_AA4B35F0720B741F0D46790C8576C04C13truncatedTextSS + 2100
	1  Lightbox                       0x1051db4dc _TTSf4gs_n___TFC8Lightbox10FooterView10updateTextfSST_ + 252
	2  Lightbox                       0x1051e8a3c _TTSf4d_n___TFC8Lightbox18LightboxControllerW11currentPageSi + 536
	3  Lightbox                       0x1051e6c08 _TFC8Lightbox18LightboxController11viewDidLoadfT_T_ + 1704
	4  Lightbox                       0x1051e6cc4 _TToFC8Lightbox18LightboxController11viewDidLoadfT_T_ + 28
	5  UIKit                          0x18c584f08 -[UIViewController loadViewIfRequired] + 1040
	6  UIKit                          0x18c584ae0 -[UIViewController view] + 28
	7  Lightbox                       0x1051e8f50 _TTSf4d_n___TFC8Lightbox18LightboxControllerW17dynamicBackgroundSb + 80
	8  Rapl                           0x104967f74 specialized QuizViewController.openImagePreview(url : String, text : String) -> () (QuizViewController.swift:388)
	9  Rapl                           0x104968128 specialized QuizViewController.previewImage(choice : Choice) -> () (QuizViewController.swift)
	10 Rapl                           0x1049655b0 protocol witness for ImageChoicePreviewDelegate.previewImage(choice : Choice) -> () in conformance QuizViewController (QuizViewController.swift)
	11 Rapl                           0x1048de8fc ImageChoiceListView.previewImage(Any) -> () (ImageChoiceListView.swift:84)
	12 Rapl                           0x1048dea2c @objc ImageChoiceListView.previewImage(Any) -> () (ImageChoiceListView.swift)
	13 UIKit                          0x18c5b9614 -[UIApplication sendAction:to:from:forEvent:] + 96
	14 UIKit                          0x18c5b9594 -[UIControl sendAction:to:forEvent:] + 80
	15 UIKit                          0x18c5a42fc -[UIControl _sendActionsForEvents:withEvent:] + 440
	16 UIKit                          0x18c5b8e88 -[UIControl touchesEnded:withEvent:] + 576
	17 UIKit                          0x18cc0f084 _UIGestureEnvironmentSortAndSendDelayedTouches + 4280
	18 UIKit                          0x18cc0a634 _UIGestureEnvironmentUpdate + 1224
	19 UIKit                          0x18cc0a118 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 404
	20 UIKit                          0x18cc09274 -[UIGestureEnvironment _updateGesturesForEvent:window:] + 276
	21 UIKit                          0x18c5b3e5c -[UIWindow sendEvent:] + 3180
	22 UIKit                          0x18c585384 -[UIApplication sendEvent:] + 340
	23 UIKit                          0x18ced285c __dispatchPreprocessedEventFromEventQueue + 2364
	24 UIKit                          0x18ced4de8 __handleEventQueueInternal + 4760
	25 UIKit                          0x18cecdd04 __handleHIDEventFetcherDrain + 152
	26 CoreFoundation                 0x1830f62e8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	27 CoreFoundation                 0x1830f6268 __CFRunLoopDoSource0 + 88
	28 CoreFoundation                 0x1830f5af0 __CFRunLoopDoSources0 + 204
	29 CoreFoundation                 0x1830f36c8 __CFRunLoopRun + 1048
	30 CoreFoundation                 0x183013fb8 CFRunLoopRunSpecific + 436
	31 GraphicsServices               0x184eabf84 GSEventRunModal + 100
	32 UIKit                          0x18c5e82f4 UIApplicationMain + 208
	33 Rapl                           0x104896ee0 main (AppDelegate.swift:32)
	34 libdyld.dylib                  0x182b3656c start + 4

The code which i am using to invoke the light box is

    let images = [
        LightboxImage(imageURL: URL(string: url)!, text: text)
    ]
    
    LightboxConfig.InfoLabel.ellipsisColor = UIColor.red;
    LightboxConfig.PageIndicator.enabled = false;
    LightboxConfig.CloseButton.enabled = false;
    
    let controller = LightboxController(images: images)
    
    if text == "" {
        controller.footerView.isHidden = true;
    }
    
    controller.headerView.isHidden = true;
    controller.dynamicBackground = true
    
    present(controller, animated: true, completion: nil)

**Comment by onmyway133** [comment]
@talk2cerlin Hi, may I ask what version of Lightbox are you using? Can you check the latest https://github.com/hyperoslo/Lightbox/releases/tag/2.1.1 which will fix this problem

**Comment by talk2cerlin** [comment]
After updating the plugin to 2.1.1, i am getting a new issue.


![screen shot 2017-11-25 at 4 05 14 pm](https://user-images.githubusercontent.com/3783401/33229730-7d552da4-d1fa-11e7-8476-5dcea106b64e.png)

**Comment by talk2cerlin** [comment]
I think updating xcode to 9.0 should fix the issue.

**Comment by onmyway133** [comment]
@talk2cerlin Yeah, we are moving to Swift 4 now
