### ISSUE TITLE
Custom buttons at the bottom

### ISSUE THREAD

**Issue by jyounus** [hyperoslo/Lightbox#164]
Hey there,

Is there currently a way to add a custom button to the bottom of the photo viewer? I'd like to add a button (or any UIView) to allow the user to perform certain actions. 

You can think of this similar to the native Photos.app on iOS. When you tap on a photo, you have a bottom bar where you can tap on the "share", "favourite" or "delete" buttons. 

If this isn't possible right now, is this something you'd consider adding? This would mimic the behaviour of the native photo app and basically be underneath the current info label. 

(Obviously the behaviour of those buttons would be defined by the developer and not by Lightbox. Lightbox would just provide a way to add buttons at the bottom, but the behaviour or what they do when tapped by the user, would be outside of the scope of this lib).

**Comment by margox** [comment]
you can create a enhanced LightboxController:
```swift
import Lightbox

public class EnhancedLightboxController: LightboxController {

  public override init(images: [LightboxImage], startIndex: Int = 0) {

    super.init(images: images, startIndex: startIndex)

    // here you can do what you want .
    self.footerView.addSubview(/* your stuff */)

  }

  required public init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }

}

```
and then use EnhancedLightboxController instead of LightboxController:
```swift
let controller = EnhancedLightboxController(images: lightBoxImages, startIndex: 1)
present(controller, animated: true, completion: nil)
```

**Comment by jyounus** [comment]
I will give that a try, thanks!

**Comment by annjawn** [comment]
I tried this method and the button shows up in the bottom, but it's not tappable. per se, when I try to tap the button the BottomView dissapears and the `touchUpInside` doesn't even register. What am I doing wrong?

```
let btn = UIButton(frame: CGRect(x: self.view.frame.midX - 80, y: frame.midY - 100, width: 160, height: 35))
btn.setTitle("Remove", for: .normal)
btn.addTarget(self, action: #selector(removed(_:)), for: .touchUpInside)
self.footerView.addSubview(btn)
```
