### ISSUE TITLE
How to show page label

### ISSUE THREAD

**Issue by turtlexuan** [hyperoslo/Lightbox#166]
Excuse me.
May I ask how to show the page label below the image like your demo photo?
![demo](https://user-images.githubusercontent.com/12083776/33643584-fe21fa2e-da7a-11e7-84eb-8361a9251b7e.png)

**Comment by onmyway133** [comment]
@turtlexuan Hi, you just need to set the `text`, see an example here https://github.com/hyperoslo/Lightbox/blob/master/Example/DemoLightbox/DemoLightbox/ViewController.swift#L29

**Comment by ulukaya** [comment]
This doesn't show up by default. Only when orient to landscape it appears, then keeps there even if I go back to vertical

**Comment by Schaefers** [comment]
Same for me, just shows up sometimes after some touch events.

**Comment by onmyway133** [comment]
@ulukaya @Schaefers Hi, we will look into it next week

**Comment by onmyway133** [comment]
@turtlexuan @ulukaya @Schaefers Hi, can you check https://github.com/hyperoslo/Lightbox/releases/tag/2.1.2 ?

**Comment by Schaefers** [comment]
Works for me, thanks!

**Comment by shusain93** [comment]
For whatever reason this is not in the main cocoapod release track? Intentional? I had to use `pod 'Lightbox', :git => 'https://github.com/hyperoslo/Lightbox.git'` to use this.

It did fix the problem though, so thanks!
