### ISSUE TITLE
How to handle authentication

### ISSUE THREAD

**Issue by AbhijeetMallick** [hyperoslo/Lightbox#171]
I have a web service which requires authentication to access image assets. In my case, authentication is simply an HTTP header.
How should we attach authentication to the image request?

**Comment by onmyway133** [comment]
@AbhijeetMallick Hi, we default to use https://github.com/hyperoslo/Imaginary to load remote image. But you can customise it to do your own networking
https://github.com/hyperoslo/Lightbox/blob/master/Source/LightboxConfig.swift#L22
