### ISSUE TITLE
Background image stretches

### ISSUE THREAD

**Issue by lmsmartins** [hyperoslo/Lightbox#174]
I've noticed the background image stretches. One of the solutions to fix this issue is to set the view's content mode as ".scaleAspectFill", so it doesn't stretch. May I submit a PR for this? See images below:

**Before:** (two moons stretched)
<img width="400" alt="before" src="https://user-images.githubusercontent.com/8367143/34873445-b79af642-f784-11e7-9a13-b448787505d7.png">

**After:** (image is scaled with .scaleAspectFill)
<img width="400" alt="after" src="https://user-images.githubusercontent.com/8367143/34873444-b77af446-f784-11e7-8de5-aa46affab6ae.png">

**Comment by johnnyperdomo** [comment]
Have you figured out a solution for this yet? I've noticed the same thing

**Comment by johnnyperdomo** [comment]
@lmsmartins Also, how did you change the button text to be an image?
