### ISSUE TITLE
Initialize Lighboxcontroller with a random index in an Images array

### ISSUE THREAD

**Issue by annjawn** [hyperoslo/Lightbox#176]
If I have an array with 5 `LightboxImage` elements and I want to initialize the `LightBoxController` at a random index , lets say index 2, how can I go about doing that?

**Comment by t0a0** [comment]
There is only one init and it supports random index.
`public init(images: [LightboxImage] = [], startIndex index: Int = 0) {}`

**Comment by annjawn** [comment]
yes i figured that one out. Thanks.
