### ISSUE TITLE
On iPhone X, camera flash and reverse camera icons in the upper corners are bordering the edge/cut off

### ISSUE THREAD

**Issue by ulukaya** [hyperoslo/Lightbox#178]
![y4dfqhtzxcc](https://user-images.githubusercontent.com/821349/35298121-26875da2-004f-11e8-88a5-3591885351f3.png)

**Comment by vadymmarkov** [comment]
@ulukaya Doesn't seem like `Lightbox` to me. If it's https://github.com/hyperoslo/ImagePicker feel free to open an issue there.

**Comment by ulukaya** [comment]
sorry, you are right.
