### ISSUE TITLE
Close button in lightbox doesn't have any background protection. If the image is white, it is hard to see the button and prevent me from closing the screen.

### ISSUE THREAD

**Issue by ulukaya** [hyperoslo/Lightbox#179]
Close button in the lightbox doesn't have any background protection. If the photo is white, it is hard to see the button and prevent me from closing the screen.

**Comment by nitrozth** [comment]
Hi, I did some workaround with headerView. here my solution:

`
controller.headerView.closeButton.shadowColor = Color.darkGray
controller.headerView.closeButton.shadowOffset = CGSize(width: 0, height: 0)
controller.headerView.closeButton.shadowRadius = 2.0
controller.headerView.closeButton.shadowOpacity = 0.8
`

**Comment by ulukaya** [comment]
closeButton is a UIButton, it doesn't have those properties. Those probs exist on UILabel

**Comment by nitrozth** [comment]
@ulukaya Sorry, i forgot that i use extension class to access those probs directly instead of using UIButton.layer
