### ISSUE TITLE
Handle the Delete button

### ISSUE THREAD

**Issue by Ivan-Cantarino** [hyperoslo/Lightbox#188]
Hello.

I've recently added the `LightBoxConfig.DeleteButton` and I cannot find any delegate to handle the `delete` action, since whenever I delete an image I have to update an outside datasource.

Any way to intercept this action?

**Comment by djaygit** [comment]
Did you find the way?

**Comment by sedwo** [comment]
@Ivan-Cantarino What was the solution to this?

**Comment by 10000TB** [comment]
@sedwo  @Ivan-Cantarino 
Use `LightboxControllerPageDelegate`
During     
```
func lightboxControllerWillDismiss(_ controller: LightboxController) {
        log.info("Will dismiss - images left: \(controller.images)")
        if controller.images.count == 0 {
             // do sth to delete previously selected image for the lightbox viewer.
        } else {
             // do nothing
        }
    }
```
(so if you only show one image at a time, if delete button was clicked, you will know controller's images will be empty when dismissing the viewer as it was deleted from viewer's list, then you can update you current view's data source and reload view.)

If you showed more than one images, it is also easy, you can pre-save a copy of what images showed, and compared that with what remains within controller at the time of dismissing, then make decision on what to delete in your current view.

**Comment by ozgurodabasi** [comment]
You can also add delete button as subview

`       let trashIcon = UIImage(named: "deleteIcon")?.withRenderingMode(.alwaysTemplate)
        let trashIconButton = UIButton(frame: CGRect(x: 14, y: 14, width: 24, height: 24))
        trashIconButton.setImage(trashIcon, for: [])
        trashIconButton.contentMode = .scaleAspectFit
        trashIconButton.tintColor = UIColor.white
        trashIconButton.addTarget(self, action: #selector(deletePhoto(_:)), for: .touchUpInside)`

and can get currentImage as 
`let currentImage = self.lightboxController.currentPage`

**Comment by 10000TB** [comment]
@ozgurodabasi like the subview idea, but it would better to add the `trashIconButton` to `controller.headerView` instead. So when, user interact with the image, it will get temporarily hidden along with the headerView instead of hanging there all the time
