### ISSUE TITLE
Possibility to open a specified page

### ISSUE THREAD

**Issue by danilolutti** [hyperoslo/Lightbox#190]
There is a way to load a specified page?
Example: 
```
let images = [... , ... , ... , ... , ... , ... , ...] 
let controller = LightboxController(images: images)
controller.startAt(2) 
present(controller, animated: true, completion: nil) //show the controller at position 2 of the array

```

**Comment by danilolutti** [comment]
solved: controller.goTo(2) is the solution.

**Comment by sibincc** [comment]
it doesnt work

**Comment by sibincc** [comment]
Hi figured out why 
let images = [... , ... , ... , ... , ... , ... , ...] 
let controller = LightboxController(images: images)
present(controller, animated: true, completion: nil) 
controller.startAt(2) 

The code should be in this sequence I know its silly but might help somebody .
