### ISSUE TITLE
forever show close button

### ISSUE THREAD

**Issue by pareekkhushboo77** [hyperoslo/Lightbox#198]
On zooming the close button hides, can we make the close button active forever.

**Comment by hardikamal** [comment]
@pareekkhushboo77 Were you able to achieve this?
@3lvis Is this feature available?

**Comment by 3lvis** [comment]
Hi @hardikamal, I don't know if the issue is still there. This project is in maintenance mode since we aren't using it anymore. If you have any suggestions I'll be happy to follow up.
