### ISSUE TITLE
How do you handle delete?

### ISSUE THREAD

**Issue by joshxplor** [hyperoslo/Lightbox#199]
is there a callback for pressing delete?

**Comment by vadymmarkov** [comment]
There is no callback atm, delete is an internal action.

**Comment by joshxplor** [comment]
Ok got. Managed to used the dismiss delegate by retrieving the existing Lightbox images and clear my datasource on controller dismiss

**Comment by vadymmarkov** [comment]
Great 👍 I'm closing this issue then.

**Comment by dknchris** [comment]
1. You can trigger the delete button using: LightboxController.headerView.deleteButton.sendActions(for: .touchUpInside)
