### ISSUE TITLE
Compatibility with Cache 5.0.0

### ISSUE THREAD

**Issue by idroxid** [hyperoslo/Lightbox#200]
Hi,

I'm working with Swift 4.1 and Cocoapods.

I'm using the Library Cache 5.1.0 for specific purposes (need the Transformer feature) and it works well.
Now, I just want to start using the Lightbox library (v 2.1.2) but when I install it using Cocoapods there is a dependency issue:

`    Lightbox (~> 2.1.2) was resolved to 2.1.2, which depends on
      Imaginary (~> 3.0) was resolved to 3.0.3, which depends on
        Cache (~> 4.0)`

Do you planned to update Imaginary/Lightbox in order to be comatible with Cache 5.1.0 ?

Many thanks !

**Comment by onmyway133** [comment]
@idroxid Hi, can you check https://github.com/hyperoslo/Lightbox/releases/tag/2.3.0 ?
