### ISSUE TITLE
not deallocating previous memory after swiping images.

### ISSUE THREAD

**Issue by kundanjadhav** [hyperoslo/Lightbox#203]
Hi,
when swiping images memory is getting allocated for new images but previous memory not getting deallocated. 

Let me know if anyone have same issue and have already got solution.

Thanks in advance

**Comment by dknchris** [comment]
This is still an issue. The issue was closed without any comment. Are we doing something wrong? The memory is not being deallocated after swiping the images as the issue is aptly named.
