### ISSUE TITLE
Support of swift 4.2 needed

### ISSUE THREAD

**Issue by romansorochak** [hyperoslo/Lightbox#208]
Support of swift 4.2 needed

**Comment by batuhangobekli** [comment]
+1

**Comment by intoxicated** [comment]
Can you update .podspec to pick right version of swift in objective c?

**Comment by subratpadhi007** [comment]
any update on this guys ? please help me out m stuck here :-(

**Comment by alexanderathan** [comment]
+1

**Comment by vitalii-tym** [comment]
_[Just a reminder to anyone who got stuck with Swift versions differences in libs]_

Until the lib is updated to newer language version, it is still possible to use it inside your Swift 4.2 project. Just add this in the end of podspec:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Lightbox'].include? target.name
            print "Setting #{target}'s SWIFT_VERSION to 4.1\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
```
This is applicable to any other libs also, even if they use different Swift versions. For example:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['SmoothTab', 'Cache', 'Imaginary', 'Lightbox', 'Popover', 'AttributedTextView', 'SwiftIcons'].include? target.name
            print "Setting #{target}'s SWIFT_VERSION to 4.1\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        else
            if ['LIHAlert'].include? target.name
                print "Setting #{target}'s SWIFT_VERSION to 3.2\n"
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.2'
                end
            end
        end
    end
end
```

**Comment by romansorochak** [comment]
@vitalii-tym 
it still does not help me 
I just added it to podfile but after pod install Xcode still says there are some errors

<img width="1428" alt="screen shot 2018-10-11 at 4 33 13 pm" src="https://user-images.githubusercontent.com/7702356/46807732-5f622200-cd73-11e8-94c1-a94e52e4c220.png">


platform :ios, '10.0'
use_frameworks!

def common_pods
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'lottie-ios'
    pod 'Hero'
    pod 'SkyFloatingLabelTextField'
    pod 'TTTAttributedLabel'
    pod 'Device'
    pod 'Firebase/Core'
    #    pod 'Fabric', '~> 1.7.6'
    pod 'Crashlytics'
    pod 'KeychainAccess'
    pod 'JRMFloatingAnimation'
    #    pod 'SDWebImage', '~> 4.0'
    pod 'LTMorphingLabel'
    pod 'ReachabilitySwift'
    pod 'Texture'
    pod 'BonMot'
    pod 'DynamicBlurView'
    pod 'QuickBlox'
    pod 'Quickblox-WebRTC'
    pod 'QMServices'
    pod 'QMChatViewController'
    pod 'Lightbox'
    pod 'ESTabBarController-swift'
    pod 'CRRefresh'
    pod 'AnimatedCollectionViewLayout'
    pod 'UPCarouselFlowLayout'
    pod 'Siren'
end

target 'Shag (Development)' do
    common_pods
end

target 'Shag (Production)' do
    common_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Lightbox'].include? target.name
            print "Setting #{target}'s SWIFT_VERSION to 4.1\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end

**Comment by vitalii-tym** [comment]
@romansorochak Check that you didn't forget to do `pod install` after adding these lines into podfile, maybe there were any errors or warnings while doing `pod install`. Also you can check the settings you have after running `pod install`, Lightbox should have `Swift 4` if everything goes correct. You can try to play with that setting manually there:

<img width="1572" alt="screenshot 2018-10-12 10 41 11" src="https://user-images.githubusercontent.com/5410835/46855617-ec0cee80-ce0c-11e8-9a4e-1d765ae0add7.png">

Your specific issue was also mentioned in an answer here: https://github.com/CocoaPods/CocoaPods/issues/8118

**Comment by vitalii-tym** [comment]
@romansorochak After catching up [my fork](https://github.com/vitalii-tym/Lightbox/tree/feature/panoramic-images-support) with the latest Lightbox I don't see any issues, Lightbox is already on Swift 4.2.
But I had the same error you have on your screenshot when I forgot to remove Lightbox from podfile's postinstall script and its language version was mistakenly set to 4. Could you please check that Lightbox has Swift 4.2 (not Swift 4) in Pods project settings? (see screenshot in my previous comment).

**Comment by Injazz** [comment]
Travis [failing](https://circleci.com/gh/hyperoslo/Lightbox/40?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for some reason

**Comment by vitalii-tym** [comment]
@Injazz it looks like you are trying to build [Cache 5.2.0](https://github.com/hyperoslo/Cache/blob/master/Cache.podspec) which is in Swift 4.2 using Xcode 9.0.1 (check the `xcodebuild -version` command in your script).

**Comment by Injazz** [comment]
it's repo's CircleCI.

**Comment by saxahan** [comment]
> @romansorochak After catching up [my fork](https://github.com/vitalii-tym/Lightbox/tree/feature/panoramic-images-support) with the latest Lightbox I don't see any issues, Lightbox is already on Swift 4.2.
> But I had the same error you have on your screenshot when I forgot to remove Lightbox from podfile's postinstall script and its language version was mistakenly set to 4. Could you please check that Lightbox has Swift 4.2 (not Swift 4) in Pods project settings? (see screenshot in my previous comment).

Unfortunately it doesn't installed with version 4.2, it was 4.0 for me too. So I had to change swift version in pods by my hand.

**Comment by idevChandra6** [comment]
I see the same errors mentioned in [#209](https://github.com/hyperoslo/Lightbox/issues/209).
Did we have a solution for this? (Post install - did not work for me.)

// Xcode 10.1
// iOS 10.3.1 and 11.0

**Comment by vitalii-tym** [comment]
@idevChandra6 
1. check that CocoaPods installs latest Lightbox (its 2.3.0 according to current podspec), do `pod update` if not

<img width="378" alt="screenshot 2018-11-22 12 31 23" src="https://user-images.githubusercontent.com/5410835/48897354-8a4f9380-ee52-11e8-8be1-1e5cd04bc427.png">

2. check that Lightbox is NOT in your post-install script
3. if steps 1 and 2 don't help - check the Swift version for Lightbox in Pods > Lighbox > Build settings. You can manually change it until your code compiles and then set that version in your post install if needed.

<img width="1249" alt="screenshot 2018-11-22 12 29 45" src="https://user-images.githubusercontent.com/5410835/48897397-a6ebcb80-ee52-11e8-8543-a23d3a4fe77d.png">

**Comment by akashBuzzyears** [comment]
> Support of swift 4.2 needed

have you found solutions for iOS newer version?
