### ISSUE TITLE
Migrate to Swift 4.2

### ISSUE THREAD

**Issue by baquer** [hyperoslo/Lightbox#209]
While Migrating to Swift 4.2 it gives these errors
![screen shot 2018-10-11 at 4 28 40 pm](https://user-images.githubusercontent.com/32494694/46799667-02666c00-cd73-11e8-9dbe-2f458d79ecd5.png)

**Comment by vitalii-tym** [comment]
@baquer there is already #208 Isn't this one a duplicate?
Or maybe you meant something different?
