### ISSUE TITLE
No such module 'Lightbox"

### ISSUE THREAD

**Issue by denikaev** [hyperoslo/Lightbox#219]
I don't understand... I used many times `pod install`, `pod update`, `sudo gem install cocoapods`. I can `import Cache` and `import Imaginary`. But every time I see `No such module 'Lightbox"`. 
Also I used cmd+shift+k it also didn't help.

Pls help me

**Comment by vnev** [comment]
Have you tried to clean and re-build the project and retry `import Lightbox`?
