### ISSUE TITLE
Need surpport for Swift 5 & Xcode 10.2.

### ISSUE THREAD

**Issue by beatman423** [hyperoslo/Lightbox#222]

**Comment by SergeyPetrachkov** [comment]
funny thing is - if you try set compatibility mode like 

```
post_install do |installer|
 installer.pods_project.targets.each do |target|
    if  target.name == 'XXX'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
    
  end
end
```

you will be able to build debug version but release build fails with `bus error 10`

**Comment by ShotJP** [comment]
+1

**Comment by weakfl** [comment]
As a workaround add this to your Podfile:
`pod 'Cache', :git => 'https://github.com/Igor-Palaguta/Cache.git', :branch => 'Update-MD5'`

**Comment by YoungchaeSong** [comment]
+1

**Comment by alexanderathan** [comment]
+1

**Comment by kientux** [comment]
Is this project no longer maintained? For Carthage users, while waiting for the owner to fix `Cache` framework issue, you can use my fork: https://github.com/kientux/Lightbox

**Comment by SebastianBO** [comment]
Kientux, been trying to get your version but its simply not working?

**Comment by kientux** [comment]
@SebastianBO I'm using my fork for my production app so I'm pretty sure it's working. Can you tell me what's your problem exactly?

**Comment by Surendraiosdev** [comment]
Currently i am using swift-3 code.
pod 'Lightbox', git: 'https://github.com/hyperoslo/Lightbox.git', branch: 'swift-3'

how can i update with swift-5?
