### ISSUE TITLE
GIF Image not supported.

### ISSUE THREAD

**Issue by tiwariammit** [hyperoslo/Lightbox#230]
Can you please add the feature to display .gif file?

**Comment by rbarbish** [comment]
Anyone have any quick solutions to this?

**Comment by Faari7** [comment]
yes please

**Comment by Faari7** [comment]
is this feature added?

**Comment by 3lvis** [comment]
Hello, we don't have plans to add it. I'm sorry.

**Comment by tiwariammit** [comment]
@Faari7 if you want to display .gif file replace the image loader library by SDWebImage library. I used these two library to load image and gif.

**Comment by fukemy** [comment]
@tiwariammit , not working to me. Can u help:
```
LightboxConfig.loadImage = { imageView, url, completion in
      imageView.sd_setImage(with: url) { image, _, _ , _ in
        completion?(image)
      }
    }
```
