### ISSUE TITLE
error with https certificate (kCFStreamErrorDomainSSL)

### ISSUE THREAD

**Issue by malkabani** [hyperoslo/Lightbox#231]
Hi

I have problem with my https certificate in the used server. so the images not appear, and it is printing error in log terminal (kCFStreamErrorDomainSSL).

Can you help me, please?

Thank you

**Comment by malkabani** [comment]
Can you please change "Imaginary" with "Kingfisher"

Thanks you

**Comment by barrylachapelle** [comment]
This would be really niiiiice. Any ideas if this will ever happen?
