### ISSUE TITLE
Latest iOS 13 build stuck on "Archiving task" Lightbox

### ISSUE THREAD

**Issue by rootux** [hyperoslo/Lightbox#234]
Does anyone were able to release an app that linked this library on iOS 13?

**Comment by sergstav** [comment]
Getting same issue on iOS 13.0, Xcode 11. Any way to resolve it?

**Comment by sergstav** [comment]
@rootux I resolved the problem. For me the problem was not in this library, but in SwiftSoup. I cant explain why Xcode stuck on LightBox, but removing SwiftSoup from project resolved and archive ok.

**Comment by giorgio80** [comment]
same for me,    it hangs on opening images :(

**Comment by yangmie** [comment]
Looks like this issue is related to default action of presenting view controller on Xcode 11, try setting 
         `lightboxController.modalPresentationStyle = .fullScreen`

**Comment by smaljaar** [comment]
@giorgio80 @yangmie check this issue description: https://github.com/hyperoslo/Lightbox/issues/229#issue-456689605 the issue you commented on is about archiving
