### ISSUE TITLE
couldn't find Assets.car

### ISSUE THREAD

**Issue by DaniKemper** [hyperoslo/Lightbox#235]
Hi, when trying to open a Image I seem to get this weird glitch. My console:

`couldn't find Assets.car in bundle with identifier: 'org.cocoapods.Lightbox'`

It seems to appear only in iOS 13.
![IMG_6673](https://user-images.githubusercontent.com/55767260/65551205-a6fca200-df21-11e9-878b-3c9ef99f3e1f.PNG)

**Comment by Kingamattack** [comment]
I have the same issue, did you find something @DaniKemper ?

**Comment by DaniKemper** [comment]
@Kingamattack I changed `controller.dynamicBackground = true`  to `controller.dynamicBackground = false` and added `controller.modalPresentationStyle = .fullScreen`. This seemed to work for me!

**Comment by Kingamattack** [comment]
Thanks a lot, I just had to change the controller.modalPresentationStyle. You can keep dynamicBackground to true
