### ISSUE TITLE
Apps freezing with error log : 'couldn't find Assets.car'

### ISSUE THREAD

**Issue by destantifw** [hyperoslo/Lightbox#237]
Application getting freeze with this error : 

> [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.Lightbox'

**Comment by SonnyMore** [comment]
I have some bug too

**Comment by SonnyMore** [comment]
check my comments please https://github.com/hyperoslo/Lightbox/issues/238

**Comment by destantifw** [comment]
thanks. my problem's solved
