### ISSUE TITLE
CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.Lightbox'

### ISSUE THREAD

**Issue by Sunny-Aiub** [hyperoslo/Lightbox#238]
CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.Lightbox'

**Comment by Sunny-Aiub** [comment]
Solved it by adding
let controller = LightboxController(images: [LightboxImage(image: image)])
 controller.modalPresentationStyle = .fullScreen
 present(controller, animated: true)

**Comment by SonnyMore** [comment]
I have this bug too, but modalPresentationStyle didn't fix it :(

**Comment by SonnyMore** [comment]
In some screen it helps, but not everywhere.

I found that if you disable animation in presenting - it works. 
also I try push this controller in navigation controller and it also work but its not a good solution)

**Comment by amit20897** [comment]
I'm having the same issue.
and your solution solved it for the displaying part, but when I dismiss the LightBoxController it freezes with the same issue (I'm checking on an iPhone Pro Max 13.1 simulator)

**Comment by 10000TB** [comment]
Having same issue on iOS 13.1.1 (built from Xcode 11.2)
