### ISSUE TITLE
.dynamicBackground does not work on ios13 devices.

### ISSUE THREAD

**Issue by objectZhang** [hyperoslo/Lightbox#244]
.dynamicBackground does not work on ios13 devices.

`lazy var effectView: UIVisualEffectView = {
    **let effect = UIBlurEffect(style: .dark)**
    let view = UIVisualEffectView(effect: effect)
    view.autoresizingMask = [.flexibleWidth, .flexibleHeight]

    return view
  }()`

thanks 🙏!

**Comment by tadeha** [comment]
Me too. iOS 13.

**Comment by jpteruel095** [comment]
Encountering errors on iOS 13 so far. I'd like to use this, but it's buggy as of the moment.

**Comment by 0xfeedface1993** [comment]
Same issue.

**Comment by summonerriftofficial** [comment]
it works for me you just need to do the following

>         let controller = LightboxController(images: [LightboxImage(imageURL: url, text: "test me")])
>         controller.modalPresentationStyle = .fullScreen
>         controller.dynamicBackground = true
>         present(controller, animated: true, completion: nil)

**Comment by summonerriftofficial** [comment]
Tested 

![Simulator Screen Shot - iPhone 11 - 2020-04-10 at 13 30 31](https://user-images.githubusercontent.com/52756966/78984650-77189300-7b2f-11ea-9768-174823a78c54.png)
