### ISSUE TITLE
Transition when presenting LightboxController

### ISSUE THREAD

**Issue by amahairides** [hyperoslo/Lightbox#255]
Hi, what I wanna do is this:
1) tap an image
2) image transitions to full screen and becomes the lightboxController

Is this already possible with your library? I could not find anything besides the internal transitioningDelegate you are using to transition to the next/previous images.

How could I do this?

Thanks

**Comment by 3lvis** [comment]
Hi @amahairides, it's not possible you might be interested in using https://github.com/3lvis/viewer

I don't think we'll expand the transitions for this library.
