### ISSUE TITLE
No options to load unsecure images

### ISSUE THREAD

**Issue by SalahAwadi91** [hyperoslo/Lightbox#257]
i cannot load images with unsecured url !!!!!!

**Comment by VaslD** [comment]
Did you enable/add App Transport Security (ATS) exceptions? AFAIK, Apple bans insecure connections by default, unless URLs are added to ATS exceptions or app has ATS disabled. You will receive warnings in Console during debugging. I don't think _Lightbox_ itself controls this behavior.

Check [this documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity) for ATS-related declarations in `Info.plist`.

**As suggested by the linked guide and as a _best practice_, you should always try to improve server-side security by adding HTTPS support first. Lowering app security should be a last resort.**

**Comment by 3lvis** [comment]
Thank you so much for answering this question @VaslD !

**Comment by 3lvis** [comment]
The answer is correct, I'll close this issue.

**Comment by SalahAwadi91** [comment]
Yes, it's working now, thank you
