### ISSUE TITLE
Can we change color of close button?

### ISSUE THREAD

**Issue by anubhavsingh16** [hyperoslo/Lightbox#260]
I can't understand how to change color of close `button` and how to change the alignment of close button. I want to change the color of close button to `blue` and placed at the left corner.

**Comment by 3lvis** [comment]
Hi @anubhavsingh16, this is not currently possible if you change it blue it might cause problems with contrast as well as some of your users might not see the button on dark backgrounds. Sorry for not being more helpful, this project is in maintenance mode and no further features are planned.
