### ISSUE TITLE
Need to show Image Preview for Video URL in LightBox Controller

### ISSUE THREAD

**Issue by hassan31** [hyperoslo/Lightbox#261]
Hi everyone,

I've implemented this control in my project and I'm adding images and videos both of the urls.. I'm wondering if I can show the thumbnail image from the video url somehow so that we can see the image preview in for video in Lightbox Controller.

Can anyone help me to find out this if already has this feature?

Look forward to hearing from you.

Thanks
Hassan

**Comment by 3lvis** [comment]
Hi @hassan31 this is not currently possible and no further features have been planned at the moment. Best.
