### ISSUE TITLE
Xcode12 build failed with Carthage

### ISSUE THREAD

**Issue by norbdev** [hyperoslo/Lightbox#263]
Carthage build failed
Latest stable Xcode 12.0 
Carthage 0.36.0
with the workaround: https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5

Imaginary
> compiling for iOS 8.0, but module 'Cache' has a minimum deployment target of iOS 9.0

https://github.com/hyperoslo/Imaginary/issues/95

**Comment by 3lvis** [comment]
Fix incoming!

**Comment by 3lvis** [comment]
We need to drop Carthage since we're having problems with it and SPM should be a preferred option

**Comment by 3lvis** [comment]
Resolved and shipped as 2.5.0
