### ISSUE TITLE
replace imaginary with kingfisher library

### ISSUE THREAD

**Issue by naveedmcs** [hyperoslo/Lightbox#284]
for performance  improvements of loading images .
I want to replace imaginary library to kingfisher library. what is possible solutions?

**Comment by chickdan** [comment]
It looks like PR #283 switched image loading libraries. 

That said I'd like to suggest that Lightbox be refactored in a way that allows developers to choose their own image loading library rather than forcing dependencies. For example I don't use SDWebImage or Kingfisher and instead use Nuke.

**Comment by naveedmcs** [comment]
@chickdan  Thanks for reply. how can i use this PR in my project? Please guide me. i will be very Thank full to you.

**Comment by mohpor** [comment]
@chickdan Dependency injection is what we need here. and I seriously second this.
