### ISSUE TITLE
Development question

### ISSUE THREAD

**Issue by alexanderkhitev** [hyperoslo/Lightbox#296]
Hey guys! Thank you for creating this great framework. I just investigate the code and I'm wondering about one thing. Why did you use `UIScrollView` as the base view instead `UICollectionView`?

**Comment by alexanderkhitev** [comment]
> Hi,
> 
> I would assume it's because `UIScrollView` is more versatile and no specific features from `UICollectionView` where required at the time.

Ok, thank you for answer. I just wondering about performance. For example: If the user opens a data set with ~ 1500 image items, can it be a problem? Thanks

**Comment by 3lvis** [comment]
If I'm not mistaken Lightbox should have pagination built-in where a few screens are reused, so 1500 image items shouldn't be a performance / memory problem.

**Comment by alexanderkhitev** [comment]
Hey @3lvis ! Ok, thank you!
