### ISSUE TITLE
Add support for orientation changing

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Lightbox#3]
Now I've just dropped landscape mode, so it always in portrait. 
@richardoti @zenangst You could try to play with it If you have some good ideas how to get it working properly in all device orientations and after zooming

**Comment by richardoti** [comment]
This question may help to solve this problem, so I'll just pin in here.
http://stackoverflow.com/questions/13490065/keeping-the-contentoffset-in-a-uicollectionview-while-rotating-interface-orienta

Also, it is good to check other implementations of these galleries in apps, how they work during orientation change.

I remember, Ole Hendrik was doing quite similar thing with map zooming, that also might help.
