### ISSUE TITLE
Version 2.5.1 missing in Cocoapods.

### ISSUE THREAD

**Issue by Zandor300** [hyperoslo/Lightbox#302]
Version 2.5.1 isn't pushed to Cocoapods. I'm currently stuck on version 2.5.0.

Please update Cocoapods to the latest version.

**Comment by 3lvis** [comment]
I don't have CocoaPods access, sorry, you will have to point to master.

**Comment by Zandor300** [comment]
@3lvis Could you please try to regain access? Because pointing at master or at a specific commit won’t work for me. I also can’t yet migrate to SwiftPM

**Comment by 3lvis** [comment]
@Zandor300 I'm sorry that won't be possible, the company that owned this repo is no longer supporting it. My advise is that you fork the repo and publish the fork to CocoaPods then point to your release. Sorry for not being more helpful.
