### ISSUE TITLE
Make config a class (or any other possibility to subclass the config)

### ISSUE THREAD

**Issue by richardoti** [hyperoslo/Lightbox#34]
Right now making a non-default config requires modifying a struct, which has to be done in the controller. I suggest making config to be a class, so it would be possible to keep it in one place and not overcomplicate controller class.

If config is a class, it is still possible for the library to work the same way (i.e. to be configured in the controller), but also, it is possible to subclass a default config, do some overrides and pass it with one line only:
```Objective-C
let mySuperConfig = MySuperConfig()
let lightBox = LightboxController(imagesUI: images, config: mySuperConfig)
```

What do you think about this?

**Comment by zenangst** [comment]
Seeing as we have a configuration now, I'm just gonna go ahead and close this one :grin:
