### ISSUE TITLE
Swift 3 and legacy support 

### ISSUE THREAD

**Issue by ashish-naik** [hyperoslo/Lightbox#81]
Hi 

I am using ImagePicker in iOS that uses Lightbox. 

I am getting below   when opened project in xcode 8. Seems Swift 3 and 2.3 are not supported yet. 

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

When will this framework support Swift 3 and 2.3?

Or is there any alternative?

Cheers
Ashish

**Comment by ashish-naik** [comment]
i updated pod file as suggested by [this article](https://medium.com/@ziminalex/xcode-8-0-cocoapods-95d8e7a769a9#.xqct7en3x)

I am using Xcode 8 final version.

However, getting below error when compiling my project.

**Xcode/Pods/Lightbox/Source/Library/LightboxTransition.swift:113:11: Initializer for conditional binding must have Optional type, not 'UIView'**

Hope this framework is getting updated soon 

Cheers
Ashish

**Comment by TheBachelor** [comment]
Still no word on this?

**Comment by RamonGilabert** [comment]
Hey there!

We were not planning to add Swift 2.3 support. But you can use the branches of ImagePicker for Swift 3 that are configured to work together.

Both branches for Lightbox and ImagePicker are called `swift-3`.

In fact, we have started using them in our projects and demo examples. It works there, so I will be closing this issue.

Feel free to reopen or keep sending messages here, I will reply asap.

**Comment by TheBachelor** [comment]
Hey @RamonGilabert is there no way to use ImagePicker and Lightbox in Swift 2.3? I'm asking because there's and example in ImagePicker's 2.3 branch that has a pod to Lightbox

**Comment by RamonGilabert** [comment]
Hey @TheBachelor, the branch of ImagePicker 2.3 was done by the community, however, I don't think the example is updated there. Lightbox doesn't have a Swift 2.3 branch, so sadly, I don't think it's possible.

You could do your own fork and then it would work, though. 😊
