### ISSUE TITLE
Picture keeps loading when setting custom downloader

### ISSUE THREAD

**Issue by euri16** [hyperoslo/Lightbox#92]
I'm setting a custom downloader for the library (alamofireimage), after the image is download and set the indicator is still visible and spinning.

**Comment by heisen273** [comment]
Same thing happens with me, I try to set image using SDWebImage library. Here is code: 

```
LightboxConfig.loadImage = {
            imageView, URL, completion in
            imageView.sd_setImage(with: URL)
        }
```

Here is result: 

![bug](https://cloud.githubusercontent.com/assets/13763176/23085844/ad8e1a9a-f572-11e6-9a0b-1925321189d8.gif)

**Comment by euri16** [comment]
I could solve it by calling the completion function after all the logic I make, i.e.:

```
LightboxConfig.loadImage = {
            imageView, URL, completion in
            imageView.sd_setImage(with: URL)

            // add this line
            completion?(response.result.error as NSError?, imageView.image)
        }
```

**Comment by heisen273** [comment]
Thanks! 

In my case I fixed it using `completion?(nil, nil)`.
