### ISSUE TITLE
Dynamic background issue

### ISSUE THREAD

**Issue by heisen273** [hyperoslo/Lightbox#96]
First of all, - Sir you have done amazing work. I love Lightbox and how it looks like. 

About the issue. I like dynamic background, however I don't understand following: 
please see this gif: 
![issue](https://cloud.githubusercontent.com/assets/13763176/23032017/c338ce32-f47b-11e6-9df6-f727d9276da9.gif)

I set startIndex like this: 

`let controller = LightboxController.init(images: photos, startIndex: indexPath.row)`

 

I have also tried this( result still the same:( ): 
```
        let controller = LightboxController.init(images: photos)
        controller.dynamicBackground = true
        controller.goTo(indexPath.row, animated: false)
```

As you can see, background is animating like scrolling from the image number 0 to selected image. 
It would be much better(and more logical: it is the first picture user clicked), if there was no background animation on startIndex image, or at least to have such option. 
I hope you understand my idea.

**Comment by vadymmarkov** [comment]
Good catch. It shouldn't be like that. Do you have any ideas @zenangst ?

**Comment by zenangst** [comment]
I can have a look at this! 😁

**Comment by andrewbellay** [comment]
I'm experiencing the exact same issue, given the exact same setup as the OP. 

I believe the issue is that **every** time remoteImageDidLoad is called (PageViewDelegate method in LightboxController), loadDynamicBackground(image) is called as well. I think the dynamic background should only be updated when the image you're looking at is updated?

Thanks & I appreciate the hard work guys!

**Comment by zenangst** [comment]
@heisen273 @andrewbellay hey guys, I just made a small PR to fix this issue. Could you guys try the `improve/dynamic-background` branch to see if that helps?

**Comment by andrewbellay** [comment]
@zenangst - This fixed the issue for me! thanks

**Comment by zenangst** [comment]
@andrewbellay glad to hear it mate, I'll get one of my co-workers to review it and when it is merged we can make a new sparkling release for you guys, cheers 🍻

**Comment by heisen273** [comment]
@andrewbellay @zenangst thank you, iOS Lords, really appreciate this!
