### ISSUE TITLE
Add buttons

### ISSUE THREAD

**Issue by heisen273** [hyperoslo/Lightbox#98]
Is there any way to add custom button? Or, for example, re-program existing "delete" button?

**Comment by oneeypi** [comment]
put a completion-handler on the delete button would be so great!

**Comment by vitalii-tym** [comment]
My intention was to make the image preview a part of JSQMessagesViewController (which is used from several places). So, I had to make the button to handle a closure, because addTarget wasn't enough for that.

So, I went this way:
1. Extended UIControl to make it possible to assign a closure as described here: https://stackoverflow.com/a/41438789/2650588
2. Did this

```
extension JSQMessagesViewController {
        ...
        // Usual Lighbox setup and configuration here
        ...
        lightbox.headerView.deleteButton.removeTarget(nil, action: nil, for: .allEvents) // I don't want the preview to disappear when button is tapped
        lightbox.headerView.deleteButton.addAction(for: .touchUpInside) {
            self.presentedViewController?.present(UIActivityViewController(activityItems: [chatImage], applicationActivities: nil), animated: true, completion: nil)
            // chatImage - is the image, which will be shown by Lighbox. I have only one image to show.
            // presentedViewController is used here because I prevent Lighbox from disappearing
        }
}
```

**Comment by vitalii-tym** [comment]
... and in case there are several images in the Lightbox, it is still possible to find out which images is currently shown and share it:

```
lightbox.headerView.deleteButton.removeTarget(nil, action: nil, for: .allEvents) // preventing this button from closing the lightbox controller
        lightbox.headerView.deleteButton.addAction(for: .touchUpInside) { [weak lightbox, weak self] in
            if let thePlaceViewController = self,
                let theLightbox = lightbox,
               let currentlyShownImage = theLightbox.images[theLightbox.currentPage].image {
                thePlaceViewController.presentedViewController?.present(UIActivityViewController(activityItems: [currentlyShownImage], applicationActivities: nil), animated: true, completion: nil)
            }
        } 
```

**Comment by sverin** [comment]
I want to add new buttons and keep both the close and delete button. How can these be achieved?

**Comment by onmyway133** [comment]
@heisen273 @sverin Hi, sorry for late response. The design of Lightbox is to have delete and close button at the header. But you can totally do your own customisation by subclassing `HeaderView` https://github.com/hyperoslo/Lightbox/blob/master/Source/Views/HeaderView.swift. Hope you understand 🥂

**Comment by sverin** [comment]
I know how to subclass the HeaderView, but I can't figure out how to use it since the headerView is set as fileprivate(set) in the LightboxController.

**Comment by onmyway133** [comment]
@sverin Hi, the proposed changes during swift 4 migration is to exposed them as `open` so that they are easier to customise. You can track the progress here xhttps://github.com/hyperoslo/Lightbox/tree/swift4, feel free to comment or review 😉

**Comment by tamoyal** [comment]
Agree that this at least seems problematic because it looks like `LightboxController` does some housekeeping on close, for example:
```
func headerView(_ headerView: HeaderView, didPressCloseButton closeButton: UIButton) {
    closeButton.isEnabled = false
    presented = false
    dismissalDelegate?.lightboxControllerWillDismiss(self)
    dismiss(animated: true, completion: nil)
  }
```

so we should probably be able to hook into that, right?
