### ISSUE TITLE
Some images always fail to load (CFNetwork internal error:304)

### ISSUE THREAD

**Issue by heisen273** [hyperoslo/Lightbox#99]
I have no clue why this happens, but for some reason some images will never be loaded. Here is example: 

1. I load image using Lightbox:
![image_bug](https://cloud.githubusercontent.com/assets/13763176/23086181/4a3097b4-f574-11e6-917c-b8f2e6504207.gif)

2. I load exact same image using another another lib(this is IDMPhotoBrowser): 

![image_succes](https://cloud.githubusercontent.com/assets/13763176/23086256/9daf44ee-f574-11e6-84ca-d4f725ac880a.gif)

This happens often with random images. 
In log I see following message: 
CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork_Sim/CFNetwork-808.2.16/Loading/URLConnectionLoader.cpp:304)

I have already tried adding in Info.plist file this lines:
![info](http://img2016.itdadao.com/d/file/tech/2016/11/16/cbb313799161045311.png) 

Still no success. All images in collection are being downloaded via HTTPS.

**Comment by heisen273** [comment]
Does anyone have any suggestion how to fix this? I would really appreciate any thoughts, thanks.

**Comment by heisen273** [comment]
I've spent many hours trying to fix it but still no luck. If anyone have any idea / experienced same issue - I would really want to hear your feedback.

**Comment by i-am-chris** [comment]
if you down the images, make sure you 
- have space on phone
- down the images
- format the images as jpg (this happenede to me once as someone made a png as jpg - renamed)
I hope it works

**Comment by heisen273** [comment]
@i-am-chris  thank you very much for suggestion, but I am 100% sure there are free space & all images are in jpg format.

**Comment by shimminZ** [comment]
did you have solve it. i have the same question.

**Comment by heisen273** [comment]
@shimminZ still nothing, my friend. Thank you very much for submitting same feedback, I was really desperate as I thought only I have this issue. 

I'd really appreciate any comments/random thoughts from Dev team or anyone else who have ever experienced CFNetwork internal error

**Comment by onmyway133** [comment]
@heisen273 Hi, this is strange, we use `Lightbox` in some apps, but haven't got this problem

**Comment by heisen273** [comment]
@onmyway133 hey, thanks for reaching me. If this might be useful, – I can give you exact image URI's that causing mentioned CFNetwork  error.

**Comment by onmyway133** [comment]
@heisen273 Hi, sorry for late response, during the swift 4 migration, we 've decided to use Imaginary to load and cache image, you can take a look here https://github.com/hyperoslo/Lightbox/pull/135. When new version is out, hopefully that will fix your problem 🥂
